### ISSUE TITLE
Error message not available

### ISSUE THREAD

**Issue by eloudsa** [ConsenSys-archive/drizzle#49]
Hi

I'm using Drizzle 1.5 within a React project 16.10.x.

My contract uses `require` function calls and returns convenient error messages:
`require(msg.send == owner, 'Only allowed to the contract owner')`

When I call my function with Drizzle and catch errors, I'm not able to get the user-friendly error message returned through the `require` call, but instead I got JSON-RPC error.

Have you noticed this problem?

Thanks

**Comment by IlgizZ** [comment]
I think it is not about drizzle, [web3 doesn't provide error message](https://github.com/ethereum/web3.js/issues/1707)

**Comment by eloudsa** [comment]
Hi @IlgizZ 
I have used another Dapp with web3 calls and I have the same effect :-(
So, you're right. It's not related to Drizzle.
Maybe a regression with Web3 (I'm using web3 1.2.2) and/or due to Ganache 2.1.1.
It's really frustrated not being able to display an understandable error message.
