### ISSUE TITLE
Ethereum provider injected by MetaMask acts differently when injected to a Dapp vs an static-website or web2 app.

### ISSUE THREAD

**Issue by alanarvelo** [ConsenSys-archive/drizzle#69]
![eth_provider_error](https://user-images.githubusercontent.com/29428052/74114732-bcddcd00-4b79-11ea-9a20-0b30b3be50bd.png)

Calling `await ethereum.send('eth_chainId')` — part of MetaMask's New API, see [here](https://medium.com/metamask/breaking-changes-to-the-metamask-inpage-provider-b4dde069dd0a) — on the console of a regular website resolves nicely (left window), while calling it in a Drizzle project fails (right window). Used the same browser and the same MM account.

It seems this issue is originated by the interaction of `web3.js` with MM's new API. It can be replicated with this test [repo](https://github.com/cds-amal/mm-exp) by @cds-amal. When the script tags which import `web3.js` are uncommented, the same `inpage.js:1 MetaMask - RPC Error: The method undefined does not exist/is not available ` error appears.

**Comment by hantuzun** [comment]
I wasn't able to reproduce this bug.
