### ISSUE TITLE
Incompatibility with Solidity 0.6 ABI's

### ISSUE THREAD

**Issue by nicholaspai** [ConsenSys-archive/drizzle#74]
0.6 ABI's are slightly different from 0.5. For example, methods in 0.6 no longer have `constant` or `payable` properties in the JSON.

One consequence is that `useCacheSend` hooks don't work (resulting in errors at run-time: `f.cacheSend is not a function`)

[Initial thread on Spectrum](https://spectrum.chat/trufflesuite/drizzle/hi-all-has-anyone-gotten-drizzle-to-play-nicely-with-solc-0-6~4f025de2-e4a1-4da3-9a83-ddecff5a2524)

**Comment by nicholaspai** [comment]
@cds-amal : In 0.6, you can replace checking for whether a function is `constant` with whether its `stateMutability` property is `view` or `pure`. Looks like you can change this in the `store` package in `src/contractStateUtils`, `src/DrizzleContract` and `types/IContract.d.ts`.

[docs](https://solidity.readthedocs.io/en/v0.5.3/abi-spec.html#json)

**Comment by ghost** [comment]
Hi there, @MalloryLeeWong and I are working on a PR that incorporates this and additional changes to make it easier to test for changes going forward. We also detected an edge case with the ABI spec that requires more testing.

The timeline is EOW or beginning of next week latest.

**Comment by nicholaspai** [comment]
Just wanted to check in here and see if any updates? Looks related to #80

**Comment by cds-amal** [comment]
Hey @nicholaspai. Apologies for the lack of response. Things have been hectic on all fronts. I'll get the ball rolling this week.

**Comment by LorenzoZaccagnini** [comment]
any update on when the xMNG PR will be merged into master?

**Comment by fakel** [comment]
> any update on when the xMNG PR will be merged into master?

I tried this PR for use with the vue-plugin and it seems to work properly.
