### ISSUE TITLE
Question about the vue plugin documentation

### ISSUE THREAD

**Issue by Draichi** [ConsenSys-archive/drizzle#81]
Is there any example of how can i configure my store on main.js (or in my store folder) ?

in the readme the only information that i have is this:

```js
// Create and configure your Vuex Store
const store = new Vuex.Store({ state: {} })
```

Can you give me an example of how to this initial state should look like?

thanks

**Comment by cds-amal** [comment]
Hi @Draichi . The Vuex Store maintains app state as a plain old JS object. Drizzle will maintain its own part of state but the rest of the app state is up to the developer to define.  It would depend on how your app defines its own internal state. Take a look at the [Vuex guide](https://vuex.vuejs.org/guide/state.html) for how state works

**Comment by Draichi** [comment]
@cds-amal thanks for you answer

My question was if I have to store the contract instance with a specific name so drizzle can know it. but it seems that drizzle will do that, drizzle itself will store a contract instance on my vuex state ?

thanks again

**Comment by cds-amal** [comment]
You’re correct. The Vue drizzle adapter will insert its contracts' instances into Vuex from `drizzleOptions`.  The Vuex object should be initialized as necessary for the Vue app.
