### ISSUE TITLE
NPM package out of date

### ISSUE THREAD

**Issue by kylescollins** [ConsenSys-archive/drizzle#99]
https://www.npmjs.com/package/drizzle

Other packages in the truffle suite have been updated, however drizzle unfortunately has not. For serverless-type architecture this causes... painful issues. 

Is there any timeline on when the truffle team may push an update for drizzle to npm? Specifically, to accommodate for the solc 0.6.0 breaking changes.

Any information regarding this would be helpful. Thanks!

**Comment by cds-amal** [comment]
Hi @kylescollins

Apologies. It's been difficult to prioritize resources for Drizzle but hope this will change in the near future.
Please use the [scoped package](https://www.npmjs.com/package/@drizzle/store) which has work to address Solidity 0.6. You'll have to change how you include drizzle in your project. 

Some helpful references
- See this [truffle test project](https://github.com/trufflesuite/drizzle/tree/develop/ui-tests/truffleV6) using solodity 0.6
- [This drizzle test project using said truffle project](https://github.com/trufflesuite/drizzle/tree/develop/ui-tests/test-0.6.0-ABI)

Hope that helps
